name: Upload Gcloud
on:
  workflow_run:
    workflows: ["Check"]
    branches: [master]
    types: [completed]
jobs:
  upload-gcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          artifact_name: build
      - name: Upload Assets
        run: gsutil cp -r build/** ${{ secrets.GCP_ASSET_BUCKET }}
